image: /home/cmarrod3/turtlebot3_ws/src/Clothy/clothy_slam/map/mapita_cafeteria_porlamañanita.pgm
mode: trinary
resolution: 0.05
origin: [-12.3, -11.2, 0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25